services:
  - type: web
    name: whatsapp-clone-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: CHAT_PASSWORD
        value: test123 